/* 
* THIS FILE IS AUTO-GENERATED. 
* TODO: Check/Adjust this file after it has been generated by the python script. 
*/

#include "r_ctsu.h"
#include "./utilities/r_touch.h"

static uint16_t wkbh_thr[] = {
     MUTUAL0_KEY00_THR, 
     MUTUAL0_KEY01_THR, 
     MUTUAL0_KEY02_THR, 
     MUTUAL0_KEY03_THR, 
     MUTUAL0_KEY04_THR, 
     MUTUAL0_KEY05_THR, 
     MUTUAL0_KEY06_THR, 
     MUTUAL0_KEY07_THR, 
     MUTUAL0_KEY08_THR, 
     MUTUAL0_KEY09_THR, 
     MUTUAL0_KEY10_THR, 
     MUTUAL0_KEY11_THR, 
     MUTUAL0_KEY12_THR, 
     MUTUAL0_KEY13_THR, 
     MUTUAL0_KEY14_THR, 
     MUTUAL0_KEY15_THR, 
     MUTUAL0_KEY16_THR, 
     MUTUAL0_KEY17_THR, 
     MUTUAL0_KEY18_THR, 
     MUTUAL0_KEY19_THR, 
};

static uint16_t wkbh_hys[] = {
     MUTUAL0_KEY00_HYS, 
     MUTUAL0_KEY01_HYS, 
     MUTUAL0_KEY02_HYS, 
     MUTUAL0_KEY03_HYS, 
     MUTUAL0_KEY04_HYS, 
     MUTUAL0_KEY05_HYS, 
     MUTUAL0_KEY06_HYS, 
     MUTUAL0_KEY07_HYS, 
     MUTUAL0_KEY08_HYS, 
     MUTUAL0_KEY09_HYS, 
     MUTUAL0_KEY10_HYS, 
     MUTUAL0_KEY11_HYS, 
     MUTUAL0_KEY12_HYS, 
     MUTUAL0_KEY13_HYS, 
     MUTUAL0_KEY14_HYS, 
     MUTUAL0_KEY15_HYS, 
     MUTUAL0_KEY16_HYS, 
     MUTUAL0_KEY17_HYS, 
     MUTUAL0_KEY18_HYS, 
     MUTUAL0_KEY19_HYS, 
};

static uint16_t wkbh_baselines[] = {
     0,//MUTUAL0_KEY00_BAS, 
     0,//MUTUAL0_KEY01_BAS, 
     0,//MUTUAL0_KEY02_BAS, 
     0,//MUTUAL0_KEY03_BAS, 
     0,//MUTUAL0_KEY04_BAS, 
     0,//MUTUAL0_KEY05_BAS, 
     0,//MUTUAL0_KEY06_BAS, 
     0,//MUTUAL0_KEY07_BAS, 
     0,//MUTUAL0_KEY08_BAS, 
     0,//MUTUAL0_KEY09_BAS, 
     0,//MUTUAL0_KEY10_BAS, 
     0,//MUTUAL0_KEY11_BAS, 
     0,//MUTUAL0_KEY12_BAS, 
     0,//MUTUAL0_KEY13_BAS, 
     0,//MUTUAL0_KEY14_BAS, 
     0,//MUTUAL0_KEY15_BAS, 
     0,//MUTUAL0_KEY16_BAS, 
     0,//MUTUAL0_KEY17_BAS, 
     0,//MUTUAL0_KEY18_BAS, 
     0,//MUTUAL0_KEY19_BAS, 
};

static ctsu_channel_setting_t wkbh_per_channel_setting[] = {
    { .ctsussc = CTSUSSC_MUTUAL0_KEY00,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY00,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY00, },/*RX: 0,TX: 18*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY01,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY01,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY01, },/*RX: 0,TX: 19*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY02,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY02,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY02, },/*RX: 0,TX: 20*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY03,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY03,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY03, },/*RX: 0,TX: 21*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY04,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY04,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY04, },/*RX: 0,TX: 26*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY05,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY05,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY05, },/*RX: 1,TX: 18*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY06,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY06,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY06, },/*RX: 1,TX: 19*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY07,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY07,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY07, },/*RX: 1,TX: 20*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY08,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY08,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY08, },/*RX: 1,TX: 21*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY09,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY09,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY09, },/*RX: 1,TX: 26*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY10,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY10,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY10, },/*RX: 4,TX: 18*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY11,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY11,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY11, },/*RX: 4,TX: 19*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY12,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY12,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY12, },/*RX: 4,TX: 20*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY13,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY13,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY13, },/*RX: 4,TX: 21*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY14,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY14,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY14, },/*RX: 4,TX: 26*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY15,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY15,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY15, },/*RX: 5,TX: 18*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY16,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY16,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY16, },/*RX: 5,TX: 19*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY17,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY17,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY17, },/*RX: 5,TX: 20*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY18,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY18,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY18, },/*RX: 5,TX: 21*/
    { .ctsussc = CTSUSSC_MUTUAL0_KEY19,  .ctsuso0 = CTSUSO0_MUTUAL0_KEY19,  .ctsuso1 = CTSUSO1_MUTUAL0_KEY19, },/*RX: 5,TX: 26*/
};

#if (MUTUAL_METHOD_NUM == 1)
#define MUTUAL0_CTSUCR0    (MUTUAL0_CTSUTXVSEL<<7)
#define MUTUAL0_CTSUCR1    ((_11_CTSUMD_MUTUAL<<6)|(_00_CTSUCLK_PCLK<<4)|(MUTUAL0_CTSUATUNE1<<3)|(_0_CTSUATUNE0_NORMAL<<2)|(_1_CTSUCSW_ON<<1)|(_1_CTSUPON_HW_POWER_ON<<0))
#define MUTUAL0_CTSUSDPRS  ((MUTUAL0_CTSUSOFF<<6)|(MUTUAL0_CTSUPRMODE<<4)|(MUTUAL0_CTSUPRRATIO<<0))
#define MUTUAL0_CTSUSST    (_00010000_CTSUSST_RECOMMEND)
#define MUTUAL0_CTSUCHAC0  (CTSUCHAC0_MUTUAL0_ENABLE_TS)
#define MUTUAL0_CTSUCHAC1  (CTSUCHAC1_MUTUAL0_ENABLE_TS)
#define MUTUAL0_CTSUCHAC2  (CTSUCHAC2_MUTUAL0_ENABLE_TS)
#define MUTUAL0_CTSUCHAC3  (CTSUCHAC3_MUTUAL0_ENABLE_TS)
#define MUTUAL0_CTSUCHAC4  (CTSUCHAC4_MUTUAL0_ENABLE_TS)
#define MUTUAL0_CTSUCHTRC0 (CTSUCHTRC0_MUTUAL0_TRANSMIT_TS)
#define MUTUAL0_CTSUCHTRC1 (CTSUCHTRC1_MUTUAL0_TRANSMIT_TS)
#define MUTUAL0_CTSUCHTRC2 (CTSUCHTRC2_MUTUAL0_TRANSMIT_TS)
#define MUTUAL0_CTSUCHTRC3 (CTSUCHTRC3_MUTUAL0_TRANSMIT_TS)
#define MUTUAL0_CTSUCHTRC4 (CTSUCHTRC4_MUTUAL0_TRANSMIT_TS)
#define MUTUAL0_CTSUDCLKC  ((_11_CTSUSSCNT<<4)|(_00_CTSUSSMOD<<0))

#define NUM_EXCLUDED (0)
#if (NUM_EXCLUDED > 0)
ctsu_channel_pair_t excluded_pairs[NUM_EXCLUDED] = {

};
#endif

uint8_t mutual0_config_binary[(sizeof(wkbh_per_channel_setting)/(sizeof(ctsu_channel_setting_t)*8))+1];
static ctsu_channel_data_mutual_t mutual0_raw_results[sizeof(wkbh_per_channel_setting)/sizeof(ctsu_channel_setting_t)];
static ctsu_channel_data_mutual_t mutual0_fil_results[sizeof(wkbh_per_channel_setting)/sizeof(ctsu_channel_setting_t)];

ctsu_hw_cfg_t g_ctsu_config_mutual = { 
    /* One Time Settings */
    .ctsu_settings = { 
		.CTSUCR0 = MUTUAL0_CTSUCR0, 
		.CTSUCR1 = MUTUAL0_CTSUCR1, 
		.CTSUSDPRS = MUTUAL0_CTSUSDPRS, 
		.CTSUSST = MUTUAL0_CTSUSST, 
		.CTSUCHAC0 = MUTUAL0_CTSUCHAC0, 
		.CTSUCHAC1 = MUTUAL0_CTSUCHAC1, 
		.CTSUCHAC2 = MUTUAL0_CTSUCHAC2, 
		.CTSUCHAC3 = MUTUAL0_CTSUCHAC3, 
		.CTSUCHAC4 = MUTUAL0_CTSUCHAC4, 
		.CTSUCHTRC0 = MUTUAL0_CTSUCHTRC0, 
		.CTSUCHTRC1 = MUTUAL0_CTSUCHTRC1, 
		.CTSUCHTRC2 = MUTUAL0_CTSUCHTRC2, 
		.CTSUCHTRC3 = MUTUAL0_CTSUCHTRC3, 
		.CTSUCHTRC4 = MUTUAL0_CTSUCHTRC4, 
		.CTSUDCLKC = MUTUAL0_CTSUDCLKC, 
        }, 
    /* Per channel settings */
    .write_settings = (ctsu_channel_setting_t*)wkbh_per_channel_setting,

    .threshold = (uint16_t*)wkbh_thr,
    .hysteresis =(uint16_t*) wkbh_hys,
    .baseline = (uint16_t*)wkbh_baselines,
    .raw_result = &mutual0_raw_results,
    .filter_output = &mutual0_fil_results,

    .binary_result = &mutual0_config_binary,
#if NUM_EXCLUDED > 0 
    .excluded = excluded_pairs, 
    .num_excluded = NUM_EXCLUDED, 
#else 
    .excluded = NULL,
    .num_excluded = 0,
#endif

};
#endif

