/* 
* THIS FILE IS AUTO-GENERATED. 
* TODO: Check/Adjust this file after it has been generated by the python script. 
*/

#include "r_ctsu.h"
#include "./utilities/r_touch.h"

static uint16_t wkbh_thr[] = {
     SELF_TS00_THR, 
     SELF_TS01_THR, 
     SELF_TS04_THR, 
     SELF_TS05_THR, 
     SELF_TS06_THR, 
     SELF_TS07_THR, 
};

static uint16_t wkbh_hys[] = {
     SELF_TS00_HYS, 
     SELF_TS01_HYS, 
     SELF_TS04_HYS, 
     SELF_TS05_HYS, 
     SELF_TS06_HYS, 
     SELF_TS07_HYS, 
};

static uint16_t wkbh_baselines[] = {
     0,//SELF_TS00_BAS, 
     0,//SELF_TS01_BAS, 
     0,//SELF_TS04_BAS, 
     0,//SELF_TS05_BAS, 
     0,//SELF_TS06_BAS, 
     0,//SELF_TS07_BAS, 
};

static ctsu_channel_setting_t wkbh_per_channel_setting[] = {
    { .ctsussc = CTSUSSC_TS00,  .ctsuso0 = CTSUSO0_TS00,  .ctsuso1 = CTSUSO1_TS00, },/*RX: 0,TX: -1*/
    { .ctsussc = CTSUSSC_TS01,  .ctsuso0 = CTSUSO0_TS01,  .ctsuso1 = CTSUSO1_TS01, },/*RX: 1,TX: -1*/
    { .ctsussc = CTSUSSC_TS04,  .ctsuso0 = CTSUSO0_TS04,  .ctsuso1 = CTSUSO1_TS04, },/*RX: 4,TX: -1*/
    { .ctsussc = CTSUSSC_TS05,  .ctsuso0 = CTSUSO0_TS05,  .ctsuso1 = CTSUSO1_TS05, },/*RX: 5,TX: -1*/
    { .ctsussc = CTSUSSC_TS06,  .ctsuso0 = CTSUSO0_TS06,  .ctsuso1 = CTSUSO1_TS06, },/*RX: 6,TX: -1*/
    { .ctsussc = CTSUSSC_TS07,  .ctsuso0 = CTSUSO0_TS07,  .ctsuso1 = CTSUSO1_TS07, },/*RX: 7,TX: -1*/
};

#if (SELF_METHOD_NUM > 0)
#define SELF_CTSUCR0    (0x00)
#define SELF_CTSUCR1    ((_01_CTSUMD_SELF_MULTI<<6)|(_00_CTSUCLK_PCLK<<4)|(SELF_CTSUATUNE1<<3)|(_0_CTSUATUNE0_NORMAL<<2)|(_1_CTSUCSW_ON<<1)|(_1_CTSUPON_HW_POWER_ON<<0))
#define SELF_CTSUSDPRS  ((SELF_CTSUSOFF<<6)|(SELF_CTSUPRMODE<<4)|(SELF_CTSUPRRATIO<<0))
#define SELF_CTSUSST    (_00010000_CTSUSST_RECOMMEND)
#define SELF_CTSUCHAC0  (CTSUCHAC0_SELF_ENABLE_TS)
#define SELF_CTSUCHAC1  (CTSUCHAC1_SELF_ENABLE_TS)
#define SELF_CTSUCHAC2  (CTSUCHAC2_SELF_ENABLE_TS)
#define SELF_CTSUCHAC3  (CTSUCHAC3_SELF_ENABLE_TS)
#define SELF_CTSUCHAC4  (CTSUCHAC4_SELF_ENABLE_TS)
#define SELF_CTSUDCLKC  ((_11_CTSUSSCNT<<4)|(_00_CTSUSSMOD<<0))

#define NUM_EXCLUDED (0)
#if (NUM_EXCLUDED > 0)
ctsu_channel_pair_t excluded_pairs[NUM_EXCLUDED] = {

};
#endif

uint8_t self_config_binary[(sizeof(wkbh_per_channel_setting)/(sizeof(ctsu_channel_setting_t)*8))+1];
static ctsu_channel_data_self_t self_raw_results[sizeof(wkbh_per_channel_setting)/sizeof(ctsu_channel_setting_t)];
static ctsu_channel_data_self_t self_fil_results[sizeof(wkbh_per_channel_setting)/sizeof(ctsu_channel_setting_t)];

ctsu_hw_cfg_t g_ctsu_config_self = { 
    /* One Time Settings */
    .ctsu_settings = { 
		.CTSUCR0 = SELF_CTSUCR0, 
		.CTSUCR1 = SELF_CTSUCR1, 
		.CTSUSDPRS = SELF_CTSUSDPRS, 
		.CTSUSST = SELF_CTSUSST, 
		.CTSUCHAC0 = SELF_CTSUCHAC0, 
		.CTSUCHAC1 = SELF_CTSUCHAC1, 
		.CTSUCHAC2 = SELF_CTSUCHAC2, 
		.CTSUCHAC3 = SELF_CTSUCHAC3, 
		.CTSUCHAC4 = SELF_CTSUCHAC4, 
		.CTSUDCLKC = SELF_CTSUDCLKC, 
        }, 
    /* Per channel settings */
    .write_settings = (ctsu_channel_setting_t*)wkbh_per_channel_setting,

    .threshold = (uint16_t*)wkbh_thr,
    .hysteresis =(uint16_t*) wkbh_hys,
    .baseline = (uint16_t*)wkbh_baselines,
    .raw_result = &self_raw_results,
    .filter_output = &self_fil_results,

    .binary_result = &self_config_binary,
#if NUM_EXCLUDED > 0 
    .excluded = excluded_pairs, 
    .num_excluded = NUM_EXCLUDED, 
#else 
    .excluded = NULL,
    .num_excluded = 0,
#endif

};
#endif

